apiVersion: v1
kind: Pod 
metadata:
  name: redis-pod
  labels:
    names: redis-pod
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
        