apiVersion: v1
kind: Service 
metadata:
  name: db
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    names: result-app-pod
    app: demo-voting-app