apiVersion: v1
kind: Pod 
metadata:
  name: voting-app-pod
  labels:
    names: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote:before
      ports:
        - containerPort: 80   